spring.application.name=livrofacil-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/livrofacil
spring.datasource.username=postgres
spring.datasource.password=100695

# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port= 8080