--
-- PostgreSQL database dump
--

\restrict mzpJOxc8h8cjV20prhRzeyfKfcWdhfFWa86Cdsfdzbhe1JxqFtapfdIgbbXKFAl

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: autor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.autor (
    aut_id bigint NOT NULL,
    aut_nome character varying(150) NOT NULL
);


ALTER TABLE public.autor OWNER TO postgres;

--
-- Name: autor_aut_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.autor ALTER COLUMN aut_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.autor_aut_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bandeira_pagamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bandeira_pagamento (
    ban_pag_disponivel character varying(1) NOT NULL,
    ban_pag_id bigint NOT NULL,
    ban_pag_nome character varying(20) NOT NULL
);


ALTER TABLE public.bandeira_pagamento OWNER TO postgres;

--
-- Name: bandeira_pagamento_ban_pag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bandeira_pagamento ALTER COLUMN ban_pag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bandeira_pagamento_ban_pag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carrinho; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carrinho (
    car_atualizado_em timestamp(6) without time zone NOT NULL,
    car_id bigint NOT NULL,
    cli_id uuid,
    car_token character varying(100) NOT NULL
);


ALTER TABLE public.carrinho OWNER TO postgres;

--
-- Name: carrinho_car_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carrinho ALTER COLUMN car_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrinho_car_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria (
    cat_id bigint NOT NULL,
    cat_nome character varying(100) NOT NULL
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- Name: categoria_cat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria ALTER COLUMN cat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_cat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    cli_ativo character varying(1),
    cli_dados_anonimizados boolean NOT NULL,
    cli_data_nascimento date,
    cli_data_cadastro timestamp(6) without time zone,
    cli_data_exclusao timestamp(6) without time zone,
    cli_numero_registro bigint NOT NULL,
    cli_cpf character varying(11),
    cli_id uuid NOT NULL,
    cli_perfil character varying(20),
    cli_telefone character varying(20),
    cli_genero character varying(30),
    cli_email character varying(50),
    cli_nome character varying(100),
    cli_senha character varying(100)
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- Name: cupom; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cupom (
    cup_ativo boolean NOT NULL,
    cup_codigo character varying(50) NOT NULL,
    cup_data_fim_vigencia date,
    cup_id bigint NOT NULL,
    cup_numero_uso_atual integer NOT NULL DEFAULT 0,
    cup_numero_uso_maximo integer,
    cup_percentual_desconto numeric(5,2),
    cup_tipo_desconto character varying(20) NOT NULL DEFAULT 'PERCENTUAL',
    cup_valor_desconto numeric(10,2)
);


ALTER TABLE public.cupom OWNER TO postgres;

--
-- Name: cupom_cup_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cupom ALTER COLUMN cup_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cupom_cup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: editora; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.editora (
    edi_id bigint NOT NULL,
    edi_nome character varying(150) NOT NULL
);


ALTER TABLE public.editora OWNER TO postgres;

--
-- Name: editora_edi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.editora ALTER COLUMN edi_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.editora_edi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: endereco; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.endereco (
    end_estado character varying(2),
    end_principal character varying(1),
    end_id bigint NOT NULL,
    end_cep character varying(10),
    cli_id uuid NOT NULL,
    end_numero character varying(20),
    end_tipo character varying(50),
    end_bairro character varying(100),
    end_cidade character varying(100),
    end_complemento character varying(100),
    end_logradouro character varying(150)
);


ALTER TABLE public.endereco OWNER TO postgres;

--
-- Name: endereco_end_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.endereco ALTER COLUMN end_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.endereco_end_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estoque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estoque (
    est_quantidade_bloqueada integer NOT NULL,
    est_quantidade_disponivel integer NOT NULL,
    est_quantidade_vendida integer NOT NULL,
    est_id bigint NOT NULL,
    liv_id bigint NOT NULL,
    CONSTRAINT ck_estoque_bloqueado_nao_negativo CHECK ((est_quantidade_bloqueada >= 0)),
    CONSTRAINT ck_estoque_disponivel_nao_negativo CHECK ((est_quantidade_disponivel >= 0)),
    CONSTRAINT ck_estoque_vendido_nao_negativo CHECK ((est_quantidade_vendida >= 0))
);


ALTER TABLE public.estoque OWNER TO postgres;

--
-- Name: estoque_est_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estoque ALTER COLUMN est_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estoque_est_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forma_pagamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forma_pagamento (
    for_pag_ativo character varying(1),
    for_pag_preferencial character varying(1),
    for_pag_ultimos_digitos character varying(4),
    for_pag_validade character varying(5),
    for_pag_criado_em timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    for_pag_id bigint NOT NULL,
    for_pag_tipo_cartao character varying(10),
    cli_id uuid NOT NULL,
    for_pag_bandeira character varying(20),
    for_pag_nome_titular character varying(100)
);


ALTER TABLE public.forma_pagamento OWNER TO postgres;

--
-- Name: forma_pagamento_for_pag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forma_pagamento ALTER COLUMN for_pag_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forma_pagamento_for_pag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grupo_precificacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grupo_precificacao (
    grp_pre_percentual_margem numeric(5,2) NOT NULL,
    grp_pre_id bigint NOT NULL,
    grp_pre_nome character varying(100) NOT NULL
);


ALTER TABLE public.grupo_precificacao OWNER TO postgres;

--
-- Name: grupo_precificacao_grp_pre_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.grupo_precificacao ALTER COLUMN grp_pre_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupo_precificacao_grp_pre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_carrinho; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item_carrinho (
    ite_car_quantidade integer NOT NULL,
    car_id bigint NOT NULL,
    ite_car_id bigint NOT NULL,
    liv_id bigint NOT NULL,
    CONSTRAINT ck_item_carrinho_quantidade_positiva CHECK ((ite_car_quantidade > 0))
);


ALTER TABLE public.item_carrinho OWNER TO postgres;

--
-- Name: item_carrinho_ite_car_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item_carrinho ALTER COLUMN ite_car_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_carrinho_ite_car_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item_pedido (
    ite_ped_quantidade integer NOT NULL,
    ite_ped_valor_unitario numeric(12,2) NOT NULL,
    ite_ped_id bigint NOT NULL,
    liv_id bigint NOT NULL,
    ped_id bigint NOT NULL,
    ite_ped_titulo character varying(200),
    CONSTRAINT ck_item_pedido_quantidade_positiva CHECK ((ite_ped_quantidade > 0)),
    CONSTRAINT ck_item_pedido_valor_nao_negativo CHECK ((ite_ped_valor_unitario >= (0)::numeric))
);


ALTER TABLE public.item_pedido OWNER TO postgres;

--
-- Name: item_pedido_ite_ped_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item_pedido ALTER COLUMN ite_ped_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_pedido_ite_ped_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: livro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.livro (
    liv_altura numeric(10,2) NOT NULL,
    liv_ano integer NOT NULL,
    liv_ativo boolean NOT NULL,
    liv_edicao integer NOT NULL,
    liv_largura numeric(10,2) NOT NULL,
    liv_numero_paginas integer NOT NULL,
    liv_peso numeric(10,2) NOT NULL,
    liv_profundidade numeric(10,2) NOT NULL,
    liv_valor_venda numeric(10,2) NOT NULL,
    aut_id bigint NOT NULL,
    edi_id bigint NOT NULL,
    grp_pre_id bigint NOT NULL,
    liv_id bigint NOT NULL,
    liv_isbn character varying(20) NOT NULL,
    liv_codigo character varying(50) NOT NULL,
    liv_codigo_barras character varying(50) NOT NULL,
    liv_titulo character varying(200) NOT NULL,
    liv_imagem_url character varying(500) NOT NULL,
    liv_sinopse character varying(5000) NOT NULL
);


ALTER TABLE public.livro OWNER TO postgres;

--
-- Name: livro_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.livro_categoria (
    cat_id bigint NOT NULL,
    liv_id bigint NOT NULL
);


ALTER TABLE public.livro_categoria OWNER TO postgres;

--
-- Name: livro_liv_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.livro ALTER COLUMN liv_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.livro_liv_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagamento_pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagamento_pedido (
    pag_ped_parcelas integer NOT NULL,
    pag_ped_valor numeric(12,2) NOT NULL,
    for_pag_id bigint NOT NULL,
    pag_ped_id bigint NOT NULL,
    ped_id bigint NOT NULL,
    CONSTRAINT ck_pagamento_parcelas_validas CHECK (((pag_ped_parcelas >= 1) AND (pag_ped_parcelas <= 12))),
    CONSTRAINT ck_pagamento_valor_positivo CHECK ((pag_ped_valor > (0)::numeric))
);


ALTER TABLE public.pagamento_pedido OWNER TO postgres;

--
-- Name: pagamento_pedido_pag_ped_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pagamento_pedido ALTER COLUMN pag_ped_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagamento_pedido_pag_ped_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedido (
    ped_desconto numeric(12,2) NOT NULL,
    ped_subtotal numeric(12,2) NOT NULL,
    ped_total numeric(12,2) NOT NULL,
    car_id bigint NOT NULL,
    ped_atualizado_em timestamp(6) without time zone,
    ped_checkout_chave bigint,
    ped_criado_em timestamp(6) without time zone NOT NULL,
    ped_id bigint NOT NULL,
    ped_reserva_expira_em timestamp(6) without time zone,
    cli_id uuid NOT NULL,
    ped_status character varying(30) NOT NULL,
    ped_cupom character varying(50),
    ped_cobranca_endereco character varying(500) NOT NULL,
    ped_entrega_endereco character varying(500) NOT NULL,
    CONSTRAINT ck_pedido_desconto_nao_negativo CHECK ((ped_desconto >= (0)::numeric)),
    CONSTRAINT ck_pedido_subtotal_nao_negativo CHECK ((ped_subtotal >= (0)::numeric)),
    CONSTRAINT ck_pedido_total_nao_negativo CHECK ((ped_total >= (0)::numeric))
);


ALTER TABLE public.pedido OWNER TO postgres;

--
-- Name: pedido_ped_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pedido ALTER COLUMN ped_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_ped_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: autor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.autor (aut_id, aut_nome) FROM stdin;
1	Robert C. Martin
\.


--
-- Data for Name: bandeira_pagamento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bandeira_pagamento (ban_pag_disponivel, ban_pag_id, ban_pag_nome) FROM stdin;
S	1	VISA
S	2	MASTERCARD
S	3	ELO
S	4	AMEX
S	5	HIPERCARD
\.


--
-- Data for Name: carrinho; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carrinho (car_atualizado_em, car_id, cli_id, car_token) FROM stdin;
2026-09-19 21:24:35.218072	1	9e30c4f0-2051-43ae-9190-b9553f7f6935	2f693489-549f-4e1b-a0c1-cfc7994361b1
2026-09-20 17:31:20.486573	2	\N	4eef6e5c-51d2-4236-8628-07eeab5118e8
2026-09-22 14:09:15.233308	3	\N	cda5ccc2-503a-43f3-96e9-ebc5d74fa44b
2026-09-22 14:18:56.880284	4	\N	352ca7bf-209f-4737-8734-94187448e583
2026-09-22 18:52:55.037567	5	a9538522-3653-4e86-ba85-6a5eeec1af63	0b32f341-f36f-43ed-bcb1-5cb68cff12fa
2026-09-22 19:19:38.52191	6	\N	7082149f-7238-4d80-9d42-b45aac0fae2f
2026-09-22 19:20:17.080692	7	\N	7e55121e-5de2-433a-8344-060e6cf8451f
2026-09-22 19:20:55.928271	8	\N	5fcb4ae2-65a0-4428-b489-0133301f5d7c
2026-09-22 19:22:12.028976	9	\N	bb307f43-5760-4cac-9c23-a6187e451492
2026-09-22 19:23:59.270897	10	\N	3e69fce0-fb4d-4459-8e93-8ead6e276f90
2026-09-22 19:25:54.362383	11	\N	b97a3d30-5301-4233-9cf2-5b69f9dfddc5
2026-09-22 19:44:30.440647	12	\N	19cc4270-6aa6-47bf-93d0-868394e61c91
2026-09-22 19:48:24.52152	13	\N	40272030-995c-485f-a8d5-a7b426daf6db
2026-09-22 19:53:38.275587	14	\N	448b2d49-f9e1-4283-ac15-bfb572db39b4
2026-09-22 20:03:38.883485	15	\N	c8355a73-baba-4590-ab1d-1bdcac260d61
2026-09-22 20:09:51.985961	16	\N	086ee998-01f0-48a6-ac6c-a4b3c5774990
2026-09-22 20:10:47.365219	17	\N	5ca0cb6d-0d6a-4f82-a0af-e4bca10b957e
2026-09-22 20:14:41.177938	18	\N	ed199061-3968-4d05-baa3-22897f9834f2
2026-09-22 20:17:32.168189	19	\N	3efa961f-d3c5-472f-a0ab-74408d0ae88f
2026-09-22 21:12:52.971694	20	\N	1f2621f7-2019-4885-b614-9371c805a2e8
2026-09-29 17:52:56.561983	21	a9538522-3653-4e86-ba85-6a5eeec1af63	a1136b29-01de-441f-b129-6614ee8ffa06
2026-09-29 18:05:17.755682	22	9e30c4f0-2051-43ae-9190-b9553f7f6935	2e25b445-1483-468e-8720-235745bac41e
2026-09-29 18:40:09.150661	23	a9538522-3653-4e86-ba85-6a5eeec1af63	edc165ea-07b5-4200-80a3-59cc98eeab74
2026-09-29 18:40:47.938931	24	9e30c4f0-2051-43ae-9190-b9553f7f6935	c0b5d634-24d6-4c09-a90c-4af54d669846
2026-09-29 18:42:12.778523	25	a9538522-3653-4e86-ba85-6a5eeec1af63	58af001e-c622-4d86-bb7b-dffe94ec78c0
2026-09-29 18:46:08.941468	26	9e30c4f0-2051-43ae-9190-b9553f7f6935	689a0d68-0a6c-4588-b100-f23706468fb4
2026-09-29 19:26:34.019344	27	a9538522-3653-4e86-ba85-6a5eeec1af63	7d465d26-44d2-434d-a6d7-578509983828
2026-09-29 19:26:51.393336	28	9e30c4f0-2051-43ae-9190-b9553f7f6935	d385dc7c-81ff-47b3-9666-fafb034a4796
2026-09-29 19:32:39.8344	29	a9538522-3653-4e86-ba85-6a5eeec1af63	38dde423-9455-432f-b7f5-6d35b07d1ae5
2026-09-29 19:39:06.825781	30	9e30c4f0-2051-43ae-9190-b9553f7f6935	a31d34c9-59f1-46e7-9e0b-2885ad2e8b15
\.


--
-- Data for Name: categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categoria (cat_id, cat_nome) FROM stdin;
1	Tecnologia
\.


--
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (cli_ativo, cli_dados_anonimizados, cli_data_nascimento, cli_data_cadastro, cli_data_exclusao, cli_numero_registro, cli_cpf, cli_id, cli_perfil, cli_telefone, cli_genero, cli_email, cli_nome, cli_senha) FROM stdin;
S	f	1990-01-01	2026-09-19 19:00:11.450771	\N	1	12345678909	9e30c4f0-2051-43ae-9190-b9553f7f6935	CLIENTE	(11) 99999-9999	FEMININO	cliente@livrofacil.com	Cliente Padrao	LivroFacil@2026
S	f	1990-01-01	2026-09-19 19:00:11.488886	\N	2	98765432100	a9538522-3653-4e86-ba85-6a5eeec1af63	ADMIN	(11) 98888-8888	MASCULINO	admin@livrofacil.com	Administrador	Admin@123
\.


--
-- Data for Name: cupom; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cupom (cup_ativo, cup_codigo, cup_data_fim_vigencia, cup_id, cup_numero_uso_atual, cup_numero_uso_maximo, cup_percentual_desconto, cup_tipo_desconto, cup_valor_desconto) FROM stdin;
\.


--
-- Data for Name: editora; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.editora (edi_id, edi_nome) FROM stdin;
1	Alta Books
\.


--
-- Data for Name: endereco; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.endereco (end_estado, end_principal, end_id, end_cep, cli_id, end_numero, end_tipo, end_bairro, end_cidade, end_complemento, end_logradouro) FROM stdin;
SP	S	1	08773-495	9e30c4f0-2051-43ae-9190-b9553f7f6935	110	casa	Mogilar	Mogi das Cruzes		Rua Antônio Ruiz Veiga
\.


--
-- Data for Name: estoque; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estoque (est_quantidade_bloqueada, est_quantidade_disponivel, est_quantidade_vendida, est_id, liv_id) FROM stdin;
0	19	1	3	2
\.


--
-- Data for Name: forma_pagamento; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.forma_pagamento (for_pag_ativo, for_pag_preferencial, for_pag_ultimos_digitos, for_pag_validade, for_pag_criado_em, for_pag_id, for_pag_tipo_cartao, cli_id, for_pag_bandeira, for_pag_nome_titular) FROM stdin;
S	S	1111	12/32	2026-09-29 18:46:29.096393	1	CREDITO	9e30c4f0-2051-43ae-9190-b9553f7f6935	VISA	Gabriela Rabello
\.


--
-- Data for Name: grupo_precificacao; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.grupo_precificacao (grp_pre_percentual_margem, grp_pre_id, grp_pre_nome) FROM stdin;
20.00	1	Livros de Tecnologia
\.


--
-- Data for Name: item_carrinho; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.item_carrinho (ite_car_quantidade, car_id, ite_car_id, liv_id) FROM stdin;
1	22	1	2
1	24	2	2
1	26	3	2
\.


--
-- Data for Name: item_pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.item_pedido (ite_ped_quantidade, ite_ped_valor_unitario, ite_ped_id, liv_id, ped_id, ite_ped_titulo) FROM stdin;
1	89.90	1	2	1	Clean Code
1	89.90	2	2	2	Clean Code
1	89.90	3	2	3	Clean Code
\.


--
-- Data for Name: livro; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.livro (liv_altura, liv_ano, liv_ativo, liv_edicao, liv_largura, liv_numero_paginas, liv_peso, liv_profundidade, liv_valor_venda, aut_id, edi_id, grp_pre_id, liv_id, liv_isbn, liv_codigo, liv_codigo_barras, liv_titulo, liv_imagem_url, liv_sinopse) FROM stdin;
23.00	2008	t	1	16.00	464	0.65	3.00	89.90	1	1	1	2	9780132350884	LIV001	9780132350884	Clean Code	https://exemplo.com/clean-code.jpg	Livro sobre boas práticas e princípios para desenvolvimento de software.
\.


--
-- Data for Name: livro_categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.livro_categoria (cat_id, liv_id) FROM stdin;
1	2
\.


--
-- Data for Name: pagamento_pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pagamento_pedido (pag_ped_parcelas, pag_ped_valor, for_pag_id, pag_ped_id, ped_id) FROM stdin;
\.


--
-- Data for Name: pedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedido (ped_desconto, ped_subtotal, ped_total, car_id, ped_atualizado_em, ped_checkout_chave, ped_criado_em, ped_id, ped_reserva_expira_em, cli_id, ped_status, ped_cupom, ped_cobranca_endereco, ped_entrega_endereco) FROM stdin;
0.00	89.90	89.90	26	2026-09-29 18:47:50.933569	\N	2026-09-29 18:46:12.49504	1	\N	9e30c4f0-2051-43ae-9190-b9553f7f6935	CANCELADO	\N	Rua Antônio Ruiz Veiga, 110 - Mogilar, Mogi das Cruzes/SP - CEP 08773-495	Rua Antônio Ruiz Veiga, 110 - Mogilar, Mogi das Cruzes/SP - CEP 08773-495
0.00	89.90	89.90	26	2026-09-29 18:48:37.36856	\N	2026-09-29 18:48:07.736189	2	\N	9e30c4f0-2051-43ae-9190-b9553f7f6935	CANCELADO	\N	Rua Antônio Ruiz Veiga, 110 - Mogilar, Mogi das Cruzes/SP - CEP 08773-495	Rua Antônio Ruiz Veiga, 110 - Mogilar, Mogi das Cruzes/SP - CEP 08773-495
0.00	89.90	89.90	26	2026-09-29 19:06:54.403481	\N	2026-09-29 18:49:48.057085	3	\N	9e30c4f0-2051-43ae-9190-b9553f7f6935	CANCELADO	\N	Rua Antônio Ruiz Veiga, 110 - Mogilar, Mogi das Cruzes/SP - CEP 08773-495	Rua Antônio Ruiz Veiga, 110 - Mogilar, Mogi das Cruzes/SP - CEP 08773-495
\.


--
-- Name: autor_aut_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.autor_aut_id_seq', 1, true);


--
-- Name: bandeira_pagamento_ban_pag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bandeira_pagamento_ban_pag_id_seq', 5, true);


--
-- Name: carrinho_car_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carrinho_car_id_seq', 30, true);


--
-- Name: categoria_cat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categoria_cat_id_seq', 1, true);


--
-- Name: cupom_cup_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cupom_cup_id_seq', 1, false);


--
-- Name: editora_edi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.editora_edi_id_seq', 1, true);


--
-- Name: endereco_end_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.endereco_end_id_seq', 1, true);


--
-- Name: estoque_est_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estoque_est_id_seq', 3, true);


--
-- Name: forma_pagamento_for_pag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.forma_pagamento_for_pag_id_seq', 1, true);


--
-- Name: grupo_precificacao_grp_pre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grupo_precificacao_grp_pre_id_seq', 1, true);


--
-- Name: item_carrinho_ite_car_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_carrinho_ite_car_id_seq', 4, true);


--
-- Name: item_pedido_ite_ped_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_pedido_ite_ped_id_seq', 5, true);


--
-- Name: livro_liv_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.livro_liv_id_seq', 2, true);


--
-- Name: pagamento_pedido_pag_ped_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pagamento_pedido_pag_ped_id_seq', 1, true);


--
-- Name: pedido_ped_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedido_ped_id_seq', 5, true);


--
-- Name: autor autor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.autor
    ADD CONSTRAINT autor_pkey PRIMARY KEY (aut_id);


--
-- Name: bandeira_pagamento bandeira_pagamento_ban_pag_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bandeira_pagamento
    ADD CONSTRAINT bandeira_pagamento_ban_pag_nome_key UNIQUE (ban_pag_nome);


--
-- Name: bandeira_pagamento bandeira_pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bandeira_pagamento
    ADD CONSTRAINT bandeira_pagamento_pkey PRIMARY KEY (ban_pag_id);


--
-- Name: carrinho carrinho_car_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrinho
    ADD CONSTRAINT carrinho_car_token_key UNIQUE (car_token);


--
-- Name: carrinho carrinho_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrinho
    ADD CONSTRAINT carrinho_pkey PRIMARY KEY (car_id);


--
-- Name: categoria categoria_cat_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_cat_nome_key UNIQUE (cat_nome);


--
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (cat_id);


--
-- Name: cliente cliente_cli_cpf_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_cli_cpf_key UNIQUE (cli_cpf);


--
-- Name: cliente cliente_cli_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_cli_email_key UNIQUE (cli_email);


--
-- Name: cliente cliente_cli_numero_registro_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_cli_numero_registro_key UNIQUE (cli_numero_registro);


--
-- Name: cliente cliente_cli_telefone_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_cli_telefone_key UNIQUE (cli_telefone);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (cli_id);


--
-- Name: cupom cupom_cup_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cupom
    ADD CONSTRAINT cupom_cup_codigo_key UNIQUE (cup_codigo);


--
-- Name: cupom cupom_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cupom
    ADD CONSTRAINT cupom_pkey PRIMARY KEY (cup_id);


--
-- Name: editora editora_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.editora
    ADD CONSTRAINT editora_pkey PRIMARY KEY (edi_id);


--
-- Name: endereco endereco_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.endereco
    ADD CONSTRAINT endereco_pkey PRIMARY KEY (end_id);


--
-- Name: estoque estoque_liv_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estoque
    ADD CONSTRAINT estoque_liv_id_key UNIQUE (liv_id);


--
-- Name: estoque estoque_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estoque
    ADD CONSTRAINT estoque_pkey PRIMARY KEY (est_id);


--
-- Name: forma_pagamento forma_pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forma_pagamento
    ADD CONSTRAINT forma_pagamento_pkey PRIMARY KEY (for_pag_id);


--
-- Name: grupo_precificacao grupo_precificacao_grp_pre_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grupo_precificacao
    ADD CONSTRAINT grupo_precificacao_grp_pre_nome_key UNIQUE (grp_pre_nome);


--
-- Name: grupo_precificacao grupo_precificacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grupo_precificacao
    ADD CONSTRAINT grupo_precificacao_pkey PRIMARY KEY (grp_pre_id);


--
-- Name: item_carrinho item_carrinho_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_carrinho
    ADD CONSTRAINT item_carrinho_pkey PRIMARY KEY (ite_car_id);


--
-- Name: item_pedido item_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_pedido
    ADD CONSTRAINT item_pedido_pkey PRIMARY KEY (ite_ped_id);


--
-- Name: livro_categoria livro_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro_categoria
    ADD CONSTRAINT livro_categoria_pkey PRIMARY KEY (cat_id, liv_id);


--
-- Name: livro livro_liv_codigo_barras_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro
    ADD CONSTRAINT livro_liv_codigo_barras_key UNIQUE (liv_codigo_barras);


--
-- Name: livro livro_liv_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro
    ADD CONSTRAINT livro_liv_codigo_key UNIQUE (liv_codigo);


--
-- Name: livro livro_liv_isbn_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro
    ADD CONSTRAINT livro_liv_isbn_key UNIQUE (liv_isbn);


--
-- Name: livro livro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro
    ADD CONSTRAINT livro_pkey PRIMARY KEY (liv_id);


--
-- Name: pagamento_pedido pagamento_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento_pedido
    ADD CONSTRAINT pagamento_pedido_pkey PRIMARY KEY (pag_ped_id);


--
-- Name: pedido pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT pedido_pkey PRIMARY KEY (ped_id);


--
-- Name: item_carrinho uk_item_carrinho_carrinho_livro; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_carrinho
    ADD CONSTRAINT uk_item_carrinho_carrinho_livro UNIQUE (car_id, liv_id);


--
-- Name: uk_cliente_numero_registro; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uk_cliente_numero_registro ON public.cliente USING btree (cli_numero_registro);


--
-- Name: endereco fk2v1us4qrddypcj2kwph8r1kpj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.endereco
    ADD CONSTRAINT fk2v1us4qrddypcj2kwph8r1kpj FOREIGN KEY (cli_id) REFERENCES public.cliente(cli_id);


--
-- Name: pedido fk31kp6l46d1v1q3b5f2acpqmrv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT fk31kp6l46d1v1q3b5f2acpqmrv FOREIGN KEY (cli_id) REFERENCES public.cliente(cli_id);


--
-- Name: livro fk5rhaa133miu22m237ek8oqdgx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro
    ADD CONSTRAINT fk5rhaa133miu22m237ek8oqdgx FOREIGN KEY (grp_pre_id) REFERENCES public.grupo_precificacao(grp_pre_id);


--
-- Name: estoque fk65f1418g1lw6kt6s2pjg1udjr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estoque
    ADD CONSTRAINT fk65f1418g1lw6kt6s2pjg1udjr FOREIGN KEY (liv_id) REFERENCES public.livro(liv_id);


--
-- Name: forma_pagamento fk6bhnih3skm5bqid6gra1irhbn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forma_pagamento
    ADD CONSTRAINT fk6bhnih3skm5bqid6gra1irhbn FOREIGN KEY (cli_id) REFERENCES public.cliente(cli_id);


--
-- Name: item_carrinho fka6cqtniw10kstiltjyrb2hcel; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_carrinho
    ADD CONSTRAINT fka6cqtniw10kstiltjyrb2hcel FOREIGN KEY (liv_id) REFERENCES public.livro(liv_id);


--
-- Name: pedido fkcl8kw41wshycnc7uxvx70l761; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT fkcl8kw41wshycnc7uxvx70l761 FOREIGN KEY (car_id) REFERENCES public.carrinho(car_id);


--
-- Name: pagamento_pedido fkdcd35pfdx9o9ablnreavojmu8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento_pedido
    ADD CONSTRAINT fkdcd35pfdx9o9ablnreavojmu8 FOREIGN KEY (for_pag_id) REFERENCES public.forma_pagamento(for_pag_id);


--
-- Name: pagamento_pedido fkgovhvecdsys8s2bdt4f3u09hw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagamento_pedido
    ADD CONSTRAINT fkgovhvecdsys8s2bdt4f3u09hw FOREIGN KEY (ped_id) REFERENCES public.pedido(ped_id);


--
-- Name: carrinho fkh5xte6b0thwe92jkifvhlxke4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carrinho
    ADD CONSTRAINT fkh5xte6b0thwe92jkifvhlxke4 FOREIGN KEY (cli_id) REFERENCES public.cliente(cli_id);


--
-- Name: item_pedido fkj78w70dbfi20utw4un3useiy9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_pedido
    ADD CONSTRAINT fkj78w70dbfi20utw4un3useiy9 FOREIGN KEY (ped_id) REFERENCES public.pedido(ped_id);


--
-- Name: livro_categoria fklwwierrgu8624b42c1s3h5k1e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro_categoria
    ADD CONSTRAINT fklwwierrgu8624b42c1s3h5k1e FOREIGN KEY (liv_id) REFERENCES public.livro(liv_id);


--
-- Name: livro fknxqaes9x70lgvupmlea326g59; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro
    ADD CONSTRAINT fknxqaes9x70lgvupmlea326g59 FOREIGN KEY (aut_id) REFERENCES public.autor(aut_id);


--
-- Name: livro fkp5t29rj6jk8hdbfxnjy23kwru; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro
    ADD CONSTRAINT fkp5t29rj6jk8hdbfxnjy23kwru FOREIGN KEY (edi_id) REFERENCES public.editora(edi_id);


--
-- Name: livro_categoria fkqennsixwdnasop301fssanq9n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.livro_categoria
    ADD CONSTRAINT fkqennsixwdnasop301fssanq9n FOREIGN KEY (cat_id) REFERENCES public.categoria(cat_id);


--
-- Name: item_pedido fkt2ni0q1ea33hgyxop38rw5efg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_pedido
    ADD CONSTRAINT fkt2ni0q1ea33hgyxop38rw5efg FOREIGN KEY (liv_id) REFERENCES public.livro(liv_id);


--
-- Name: item_carrinho fkti7hvrogvmjeuoobaitlrib0l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_carrinho
    ADD CONSTRAINT fkti7hvrogvmjeuoobaitlrib0l FOREIGN KEY (car_id) REFERENCES public.carrinho(car_id);


--
-- PostgreSQL database dump complete
--

\unrestrict mzpJOxc8h8cjV20prhRzeyfKfcWdhfFWa86Cdsfdzbhe1JxqFtapfdIgbbXKFAl

